# Read more about setting it up
# https://medium.com/@ljmocic/deploying-react-application-to-aws-s3-using-github-actions-85addacaeace

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.x
        uses: actions/checkout@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
        env:
           CI: false
      - name: Generate build
        run: npm run build
        env:
           CI: false
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
          with:
            args: --acl public-read --follow-symlinks --delete
          env:
              AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
              SOURCE_DIR: 'build'      # optional: defaults to entire repository
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: build