# Read more about setting it up
# https://medium.com/@ljmocic/deploying-react-application-to-aws-s3-using-github-actions-85addacaeace

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.x
        uses: actions/checkout@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
        env:
           CI: false
      - name: Generate build
        run: npm run build
        env:
           CI: false
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: build